### ISSUE TITLE
You are not allowed to transition swapchain images without acquiring them

### ISSUE THREAD

**Issue by ratchetfreak** [disks86/SchaeferGL#2]
https://github.com/disks86/SchaeferGL/blob/058b0338e8bd01f38a86b3ac06e83edbef46eaa7/SchaeferGL-Library/CDevice9.cpp#L1024

Here you transition the swapchain images after creating the swapchain. [This is not allowed without first having acquired them.](https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#_wsi_swapchain)

> Use of a presentable image must occur only after the image is returned by vkAcquireNextImageKHR, and before it is presented by vkQueuePresentKHR. **This includes transitioning the image layout and rendering commands.**

[Instead you a `oldImageLayout` of UNDEFINED after acquire](https://github.com/disks86/SchaeferGL/blob/058b0338e8bd01f38a86b3ac06e83edbef46eaa7/SchaeferGL-Library/CDevice9.cpp#L1398). Transitioning way from undefined is always allowed.

For more info see: http://stackoverflow.com/q/37524032/731620

**Comment by disks86** [comment]
Good catch, I just committed a fix.
