### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [disks86/SchaeferGL#3]
[An extra null pointer check is not needed](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") in [the destructor for the class "C9"](https://github.com/disks86/SchaeferGL/blob/38feaea4b9e740259248d6c6c21dfdec77dec0d4/SchaeferGL-Library/C9.cpp#L177 "Update candidate: C9 destructor").

**Comment by disks86** [comment]
Force of habit, I'll take a look this evening. Thank you for the feedback.

**Comment by disks86** [comment]
I've committed a fix for this.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/disks86/SchaeferGL/commit/b532fd260bd0786a9e50622a060e3415ccd4157a "Deletion of a few unnecessary checks").

**Comment by elfring** [comment]
Will [Vulkan destroy functions](https://www.khronos.org/registry/vulkan/specs/1.0/apispec.html#vkDestroyInstance "Clarification for vkDestroyInstance()?") tolerate also [the passing of null handles](https://github.com/disks86/SchaeferGL/blob/b532fd260bd0786a9e50622a060e3415ccd4157a/SchaeferGL-Library/C9.cpp#L177 "Update candidates remaining?")?

**Comment by disks86** [comment]
I'm not sure. It's unclear based on what I've read in the spec so far. If it's not in the spec drivers may act differently. If you find something that indicates they do in the spec let me know. They may add that in a future revision if it's not in the current one.

**Comment by elfring** [comment]
Would you like to achieve further clarification for the handling of null handles by the evolving Vulkan programming interface?
