### ISSUE TITLE
Probably safer to do nothing in begin/endScene 

### ISSUE THREAD

**Issue by axeldavy** [disks86/SchaeferGL#5]
Hi from the gallium Nine team,

Here
https://github.com/disks86/SchaeferGL/blob/master/SchaeferGL-Library/CDevice9.cpp#L1375

It's probably a bad idea to do any work in beginScene and endScene. It has been noted in some reports
by windows drivers that apps don't respect the spec with them (ie they can do rendering without calling them, or call more beginScene than endScene, or whatever).

Good luck !
Don't hesitate come on our irc chan #d3d9 to discuss, it's always useful to discuss what one finds, even if the projects are different.

**Comment by disks86** [comment]
Thank you for the heads up. It sounds like I'll need to do a render pass for each draw call then. I'll look at this tonight.

**Comment by disks86** [comment]
I committed an update that moved the logic out of the begin/end scene functions. I'm waiting until present to end the scene now and I begin it when begin is called or any of the draw methods. I'm still working on them though so I can't fully test this other than the fact it didn't cause the original sample to regress on my AMD test machine.
