### ISSUE TITLE
D3DFILL_WIREFRAME case not handled correctly in ConvertFillMode, Utilities.h line 89-90

### ISSUE THREAD

**Issue by stevenhoving** [disks86/SchaeferGL#6]
I just cloned your project and noticed something that what could be a typo.
https://github.com/disks86/SchaeferGL/blob/master/SchaeferGL-Library/Utilities.h#L89

```
case D3DFILL_WIREFRAME:
    break;
    output = VK_POLYGON_MODE_LINE;
```

The obvious fix would be:
```
case D3DFILL_WIREFRAME:
    output = VK_POLYGON_MODE_LINE;
    break;
```

**Comment by disks86** [comment]
Good catch, you are correct it was a typo. I've committed a fix for this. Thank you for your feedback.
