### ISSUE TITLE
Shaders.rc TRI_FRAG and TRI_VERT points to 'C:\VulkanSDK\1.0.13.0' but should point to 'C:\VulkanSDK\1.0.17.0'

### ISSUE THREAD

**Issue by stevenhoving** [disks86/SchaeferGL#8]
I wonder, shouldn't you pull these files into your repo?

**Comment by disks86** [comment]
Ultimately I think I'll end up modifying them. Once I get the vertex buffer working I'll need to do some refactoring. At this point I'm still working on getting the vertices to render to the screen. I'm working on the code to fill/write/update the descriptor set right now. I think that is the last piece I'm missing. After that I'll need to look into handling different buffer layouts. There are flags that control that so I'll need to setup the layout accordingly. I may need to update the shader programs to handle this as well. Also pulling shader programs from a resource was giving me an error so I'm testing with the files currently.

**Comment by disks86** [comment]
My latest commit contains a fix for this item. I've re-pointed to the new SDK sample.
